logo: /assets/logo.png
email: archives@madamekarine.com
phone: 438-380-5858
sections:
  - component: TemplateTitle
    bind:
      class: bg-white
    params:
      background:
        url: images/AP-D0340-043-COFFIN-WILBERT.jpeg
      title1:
        text: Archives
        animation:
          - up-50-easeInBack
          - fadein
        class: font-neutra text-primary text-4xl font-medium uppercase
      title2:
        text: Madame
        animation:
          - down-100-easeInBack
          - fadein-100
        class: font-neutra text-primary text-4xl font-medium uppercase
      title3:
        text: Karine
        animation:
          - down-50-easeInBack
          - fadein-100
        class: font-neutra text-primary text-4xl font-medium uppercase
  - component: TemplateCardWithImages
    nav: Qui
    bind:
      class: bg-white
    params:
      title:
        text: Qui sommes-nous?
        class: font-neutra text-4xl text-primary font-extrabold uppercase
        animation:
          - up-50
          - fadein
      subTitle:
        text: ''
        class: font-neutra-thin text-black font-bold uppercase
        animation: 'up-100, fadein'
      content:
        text: >-
          L’entreprise Madame Karine a été fondée en 2009 par Karine Perron
          recherchiste audiovisuelle et membre de l’Association des archivistes
          audiovisuels du Canada. Dix ans plus tard, Madame Karine acquière la
          collection Allo Police dans le but de conserver ce merveilleux
          patrimoine québécois riche de 50 ans d’histoire criminelle.  En 2023,
          elle s’est officiellement agrandit pour dévernir Archives Madame
          Karine inc., une équipe de recherche spécialisée en
          audiovisuelle.<br/>
          <br/>
          Dynamiques curieuses et consciencieuses, notre
          efficacité hors pair saura vous convaincre de nous confier vos projets
          pour votre plus grande tranquillité d’esprit.
        class: text-black-900 text-base
        animation:
          - up-25
          - fadein
      images:
        - src: /assets/images/AP-D0340-043-COFFIN-WILBERT.jpeg
          alt: AP-D0340-04
          animation:
            - up
            - fadein
        - src: /assets/images/AP-D0307-027-EBOULEMENTS-1974.jpeg
          alt: AP-D0307-027
          animation:
            - down
            - fadein
  - component: TemplateCardWithImages
    nav: Services
    bind:
      class: bg-primary
    params:
      title:
        text: Nos services
        class: font-neutra text-4xl text-black-900 font-extrabold uppercase
        animation:
          - up-50
          - fadein
      subTitle:
        text: ''
        class: font-neutra-thin text-white font-bold uppercase
        animation:
          - up-100
          - fadein
      content:
        text: >-
          Nous proposons un service clé en main aux producteurs télévisuels,
          musées, éditeurs et aux producteurs multimédias. Dès la première
          ébauche de votre projet, nous pouvons vous guider pour élaborer un
          budget et sa faisabilité légale. Nous offrons la recherche, la
          négociation et la libération des droits de diffusion et grâce à un
          méthodologie rigoureuse nous suivons le processus du début à la fin en
          collaboration étroite avec vos équipes.
        class: text-white text-base
        animation:
          - up-25
          - fadein
      images:
        - src: /assets/images/AP-D00709-03-METRO-MTL.jpeg
          alt: AP-D0340-04
          animation:
            - up
            - fadein
        - src: /assets/images/AP-D00709-05-METRO-MTL.jpeg
          alt: AP-D0307-027
          animation:
            - down
            - fadein
  - component: TemplateCardWithImages
    nav: Collection
    bind:
      class: bg-white
    params:
      title:
        text: Notre Collection
        class: font-neutra text-4xl text-primary font-extrabold uppercase
        animation:
          - up-50
          - fadein
      subTitle:
        text: ''
        class: font-neutra-thin text-black font-bold uppercase
        animation:
          - up-100
          - fadein
      content:
        text: |
          La collection Allo Police couvre l’histoire criminelle de 1953 à 2004.
          Elle représente est constituée de milliers de photographies et
          iapositives et de toutes les publications depuis sa
          sortie.<br/>
          <br/>
          Nous nous sommes donnés pour mission de la conserver
          et de la numériser pour qu’elle puisse vivre encore longtemps. Nous
          proposons un service de recherche pour vos demandes spécifiques et
          pouvons émettre une licence d’utilisation selon votre projet. Vous
          pouvez nous contacter pour connaitre les tarifs en vigueur.
        class: text-black text-base
        animation:
          - up-25
          - fadein
      images:
        - src: /assets/images/JOURNAL ALLO POLICE.jpeg
          alt: AP-D0340-04
          animation:
            - up
            - fadein
        - src: /assets/images/AP-D00708-04-MONTREAL-OF-SET.jpeg
          alt: AP-D0307-027
          animation:
            - down
            - fadein
  - component: TemplateCardWithClients
    nav: Nos clients
    params:
      background:
        src: /assets/images/AP-D00666-25-DELUGE-THETFORD.jpeg
        animation:
          - down-15
          - fadein
      title:
        text: Nos clients
        class: font-neutra text-4xl text-primary font-extrabold uppercase
        animation:
          - up-50
          - fadein
      subTitle:
        text: ''
        class: font-neutra-thin text-white font-bold
        animation:
          - up-100
          - fadein
      content:
        text: ''
        class: text-white text-lg uppercase
        animation:
          - up-25
          - fadein
      client:
        class: font-neutra text-white text-4xl font-extrabold uppercase
      clients:
        - Les Productions Pixcom
        - KOTV
        - TORQ Le Groupe
        - Saturne 5
        - Trio Orange
        - Groupe Fair-Play
        - Babel Films
        - Zone 3
        - Couzin Films
        - Office National du Film du Canada
        - Radio-Canada
        - Les productions Déferlantes
        - Picbois productions
        - Blimp Télé
        - Les productions Avanti-Toast Inc.
        - Urbania
        - Sphère Média Inc.
        - Terre Innue Productions
        - Télévision Illimitée
        - A Média inc.
        - Iprod inc
        - Bazzo Bazzo
        - Comedia Ha !
        - Savoir Média
        - Les Films Du Désert Blanc
        - Roméo et Fils
        - TC Média Livres
        - Les Éditions de l’Homme
        - Dokoma
        - Musée Pointe-à-Callière
        - Musée Maritime du Québec
      images:
        - src: /assets/images/JOURNAL ALLO POLICE.jpeg
          alt: AP-D0340-04
          animation:
            - up
            - fadein
        - src: /assets/images/AP-D00708-04-MONTREAL-OF-SET.jpeg
          alt: AP-D0307-027
          animation:
            - down
            - fadein
  - component: TemplateCardWithItems
    nav: Équipe
    bind:
      class: bg-white
    params:
      title:
        text: Notre équipe
        class: font-neutra text-4xl text-primary font-extrabold uppercase
        animation:
          - up-50
          - fadein
      subTitle:
        text: ''
        class: font-neutra-thin font-bold uppercase
        animation:
          - up-100
          - fadein
      content:
        text: ''
        class: text-lg
        animation:
          - up-25
          - fadein
      item:
        name:
          class: 'font-neutra-condensed text-primary text-xl font-medium leading-tight uppercase'
        title:
          class: 'font-neutra-medium text-black-900 font-medium leading-tight'
        email:
          class: 'font-neutra text-base'
      items:
        - name: Karine Perron
          title: Présidente / Recherchiste audiovisuelle sénior
          email: kperron@madamekarine.com
          src: /assets/team/Karine Perron.png
          animation:
            - up-33
            - fadein
        - name: Zoé Rabatel
          title: Recherchiste audiovisuelle
          email: zrabatel@madamekarine.com
          src: /assets/team/Zoe Rabatel.JPEG
          animation:
            - up-76
            - fadein
        - name: Léa Formigli
          title: Recherchiste audiovisuelle
          email: lformigli@madamekarine.com
          src: /assets/team/Lea Formigli.jpg
          animation:
            - up-100
            - fadein
        - name: Emy Langlois-Brien
          title: Recherchiste audiovisuelle junior /Responsable de la collection Allo Police
          email: elangloisbrien@madamekarine.com
          src: /assets/team/Emy Langlois-Brien.jpg
          animation:
            - up-100
            - fadein'
